version: '3'

services:
  #
  # MySQL
  #
  mysql:
  #  cpu_shares: 128
  #  mem_limit: 512m
    restart: unless-stopped
    build:
      context: ./containers/mysql
      args:
        - UID=${UID}
        - GID=${GID}
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
    image: libertempo/mysql
    container_name: lt-mysql
    ports:
      - 3306:3306
    networks:
        public_net2:
            ipv4_address: ${MYSQL_IP}
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}

  #
  # LDAP
  #
  # Create a mini ldap client container for boostraping data in the server
  ldap:
  #  cpu_shares: 128
  #  mem_limit: 512m
    container_name: lt-ldap
    image: actualys/ldap:1.1
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_DOMAIN: libertempo
      LDAP_PASSWORD: admin

  #
  # Apache
  #
  httpd:
  #  cpu_shares: 128
  #  mem_limit: 512m
    restart: unless-stopped
    build:
      context: ./containers/httpd
      args:
        - UID=${UID}
        - GID=${GID}
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
    image: libertempo/httpd
    container_name: lt-httpd
  # dns: 8.8.8.8
  # dns_opt:
  #   - use-vc
  #   - no-tld-query
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    links:
      - mysql:mysql
      - ldap:ldap
    volumes:
      - ${PATH_WEB}:${APACHE_ROOT_DIR}/htdocs/web
    networks:
       public_net2:
           ipv4_address: ${APACHE_IP}
    environment:
        - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
        - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
        - PHP_IP=${PHP_IP}
        - PHP_APP_DIR=${PHP_APP_DIR}
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
  #
  # PHP
  #
  php:
  #  cpu_shares: 128
  #  mem_limit: 512m
    restart: unless-stopped
    build:
      context: ./containers/php
      args:
        - UID=${UID}
        - GID=${GID}
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        - PHP_APP_DIR=${PHP_APP_DIR}
    image: libertempo/php
    container_name: lt-php
    dns: 8.8.8.8
  #  dns_opt:
  #    - use-vc
  #    - no-tld-query
    depends_on:
      - mysql
      - ldap
      - httpd
    networks:
        public_net2:
            ipv4_address: ${PHP_IP}
    volumes:
      - ${PATH_WEB}:${PHP_APP_DIR}/web
      - ${PATH_API}:${PHP_APP_DIR}/api
    extra_hosts:
        - "libertemp:${APACHE_IP}"
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - APACHE_IP=${APACHE_IP}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_IP=${MYSQL_IP}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
    public_net2:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
