version: '3'

services:
  #
  # MySQL
  #
  mysql:
  #  cpu_shares: 128
  #  mem_limit: 512m
    restart: unless-stopped
    build:
      context: ./containers/mysql
    image: libertempo/mysql
    container_name: lt-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  #
  # LDAP
  #
  ldap:
  #  cpu_shares: 128
  #  mem_limit: 512m
    container_name: lt-ldap
    image: actualys/ldap:1.1
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_DOMAIN: libertempo
      LDAP_PASSWORD: admin

  #
  # Apache
  #
  httpd:
  #  cpu_shares: 128
  #  mem_limit: 512m
    restart: unless-stopped
    build:
      context: ./containers/httpd
      args:
      - UID=${UID}
      - GID=${GID}
    image: libertempo/httpd
    container_name: lt-httpd
    dns: 8.8.8.8
  #  dns_opt:
  #    - use-vc
  #    - no-tld-query
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    links:
      - mysql:mysql
      - ldap:ldap
    depends_on:
      - mysql
      - ldap
  #
  # PHP
  #
  php:
  #  cpu_shares: 128
  #  mem_limit: 512m
    restart: unless-stopped
    build:
      context: ./containers/php
      args:
        - UID=${UID}
        - GID=${GID}
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
    image: libertempo/php
    container_name: lt-php
    dns: 8.8.8.8
  #  dns_opt:
  #    - use-vc
  #    - no-tld-query
    depends_on:
      - mysql
      - ldap
      - httpd
    volumes:
      - ${PATH_WEB}:${PHP_APP_DIR}/web
      - ${PATH_API}:${PHP_APP_DIR}/api
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - APACHE_IP=${APACHE_IP}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_IP=${MYSQL_IP}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
